name: Update bot repository with new translations

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh api repos/prosperitybot/bot/actions/workflows/18759662/dispatches -f ref=main
